version: '3'

services:
  apache:
    image: httpd:latest
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/html
      - ./httpd/httpd.conf:/usr/local/apache2/conf/httpd.conf
    depends_on:
      - php

  php:
    image: php:8.2-fpm
    build: /php
    working_dir: /var/www/php
    volumes:
      - ./src:/var/www/html